{% set name = "sphinx-markdown-tables" %}
{% set version = "0.0.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6bc6d3d400eaccfeebd288446bc08dd83083367c58b85d40fe6c12d77ef592f1

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - markdown >=3.0.1
    - python >={{ python_min }}
    - recommonmark

test:
  imports:
    - sphinx_markdown_tables
  requires:
    - sphinx
    - python {{ python_min }}
  files:
    - test.md

about:
  home: https://github.com/ryanfox/sphinx-markdown-tables
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: A Sphinx extension for rendering tables written in markdown
  description: |
    Sphinx supports markdown via Recommonmark, which does not support
    tables. This extension provides them.
  doc_url: https://pypi.org/project/sphinx-markdown-tables/
  dev_url: https://github.com/ryanfox/sphinx-markdown-tables/
  doc_source_url: https://github.com/ryanfox/sphinx-markdown-tables/blob/master/README.md

extra:
  recipe-maintainers:
    - nowster
    - benjamb
